stages:
  - build

build_mobile_apps_android:
  stage: build
  image: registry.gitlab.com/lemra/awesomedev/flutter:latest
  before_script:
    - flutter upgrade
  script:
    - flutter build apk --debug
  artifacts:
    when: always
    paths:
    - build/app/outputs/

# TODO
build_mobile_apps_ios:
  stage: build
  # TODO Find a way to include IOS Dev tools in the image
  image: registry.gitlab.com/lemra/awesomedev/flutter:latest
  before_script:
    - flutter upgrade
  script:
    - flutter build ios --debug
     || echo "TODO | CI for IOS Builds not Implemented as yet"
  artifacts:
    when: always
    paths:
    - build/app/outputs/
