#
# Extra-services, deployed to tools.rm3l.org
#

version: '3.3'

#networks:
#  management:
#  app:

services:
  #
  # Reverse Proxy
  #
  reverse-proxy:
    build: ./reverse-proxy
    ports:
      - "5180:8080"
      - "172.20.0.1:5181:8081"
    volumes:
      - /home/ci/.data:/data
    labels:
      org.rm3l.services.service_name: "reverse-proxy"
      org.rm3l.services.service_description: "Microservice for proxying requests to any other remote server"
      org.rm3l.services.service_url: "http://tools.rm3l.org:5180"
      org.rm3l.services.management_url: "http://172.20.0.1:5181"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/management/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: always

  #
  # GraphQL API against the IANA Service Names and Port Numbers Registry
  #
  iana-service-names-port-numbers:
    image: rm3l/iana-service-names-port-numbers
    ports:
      - "5280:8080"
      - "172.20.0.1:5281:8081"
    labels:
      org.rm3l.services.service_name: "iana-service-names-port-numbers"
      org.rm3l.services.service_description: "GraphQL API against the IANA Service Names and Port Numbers Registry"
      org.rm3l.services.service_url: "http://tools.rm3l.org:5280"
      org.rm3l.services.management_url: "http://172.20.0.1:5281"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/management/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: always
    entrypoint: java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar -Dsecurity.basic.enabled=true -Dmanagement.security.enabled=true -Dsecurity.user.password="R<Dwp)uK,]:%\"j7}88:B8K(]5(<>'YEkLGF'4Hf+z'<Rcu_d7sQ}]zHKY~<n[p_n" /root/iana-service-names-port-numbers.jar
    # TODO Override command to include specific application properties with security enabled (or not) :)
#    networks:
#      - management
#      - app
