version: 2.1

jobs:
  build_backend:
    working_directory: ~/dev-feed-src/backend

    docker:
      - image: adoptopenjdk:11-jdk-openj9

    steps:
      - checkout:
          path: ~/dev-feed-src
      
      - run:
          name: Output relevant env. variables
          command: echo "CIRCLE_PULL_REQUEST=$CIRCLE_PULL_REQUEST" && 
            echo "CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM" && 
            echo "CIRCLE_SHA1=$CIRCLE_SHA1"
      
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: Build
          command: ./gradlew build --stacktrace
      
      - store_artifacts:
          path: build/libs
          destination: libs

      - store_artifacts:
          path: build/reports
          destination: reports

      - store_test_results:
          path: build/test-results


  build_android:
    working_directory: ~/dev-feed-src/mobile

    docker:
      - image: cirrusci/flutter:stable

    steps:
      - checkout:
          path: ~/dev-feed-src

      - run:
          name: Output relevant env. variables
          command: echo "CIRCLE_PULL_REQUEST=$CIRCLE_PULL_REQUEST" && 
            echo "CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM" && 
            echo "CIRCLE_SHA1=$CIRCLE_SHA1"
      
      - run:
          name: Build APK
          command: flutter build apk
      
      - store_artifacts:
          path: build/app/outputs/apk
          destination: outputs

      - store_artifacts:
          path: build/reports
          destination: reports

  build_ios:
    working_directory: ~/dev-feed-src/mobile

    docker:
      - image: cirrusci/flutter:stable

    steps:
      - checkout:
          path: ~/dev-feed-src

      - run:
          name: Output relevant env. variables
          command: echo "CIRCLE_PULL_REQUEST=$CIRCLE_PULL_REQUEST" && 
            echo "CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM" && 
            echo "CIRCLE_SHA1=$CIRCLE_SHA1"

      - run:
          name: Build IOS
          command: flutter build ios || echo "IOS Builds not supported yet"
      
      - store_artifacts:
          path: build/app/outputs/ios
          destination: outputs

      - store_artifacts:
          path: build/reports
          destination: reports

  test_mobile:
    working_directory: ~/dev-feed-src/mobile

    docker:
      - image: cirrusci/flutter:stable

    steps:
      - checkout:
          path: ~/dev-feed-src

      - run:
          name: Output relevant env. variables
          command: echo "CIRCLE_PULL_REQUEST=$CIRCLE_PULL_REQUEST" && 
            echo "CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM" && 
            echo "CIRCLE_SHA1=$CIRCLE_SHA1"
      
      - run:
          name: flutter doctor
          command: flutter doctor

      - run:
          name: Run Tests
          command: flutter test

      - store_test_results:
          path: build/test-results

      - store_test_results:
          path: build/test-results

workflows:
  version: 2

  build_and_test_backend:
    jobs:
      - build_backend

  build_and_test_mobile_apps:
    jobs:
      - build_android
      - build_ios
      - test_mobile