version: 2.1

jobs:
  build_backend:
    working_directory: ~/awesome-dev-src/backend

    docker:
      - image: openjdk:8-jdk

    steps:
      - checkout:
          path: ~/awesome-dev-src
      
      - run:
          name: Output relevant env. variables
          command: echo "CIRCLE_PULL_REQUEST=$CIRCLE_PULL_REQUEST" && 
            echo "CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM" && 
            echo "CIRCLE_SHA1=$CIRCLE_SHA1"
      
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}

      - run:
          name: Build
          command: ./gradlew build --stacktrace
      
      - store_artifacts:
          path: build/libs
          destination: libs

      - store_artifacts:
          path: build/reports
          destination: reports

      - store_test_results:
          path: build/test-results


  build_android:
    working_directory: ~/awesome-dev-src/mobile

    docker:
      - image: cirrusci/flutter

    steps:
      - checkout:
          path: ~/awesome-dev-src

      - run:
          name: Output relevant env. variables
          command: echo "CIRCLE_PULL_REQUEST=$CIRCLE_PULL_REQUEST" && 
            echo "CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM" && 
            echo "CIRCLE_SHA1=$CIRCLE_SHA1"
      
      - restore_cache:
          key: jars-{{ checksum "android/build.gradle" }}-{{ checksum  "android/build.gradle" }}

      - run:
          name: Download Dependencies
          command: cd android && ./gradlew androidDependencies --stacktrace

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "android/build.gradle" }}-{{ checksum  "android/maoni-sample/build.gradle" }}
      
      - run:
          name: flutter doctor
          command: flutter doctor

      - run:
          name: Run Tests
          command: flutter test
      
      - run:
          name: Build APK
          command: flutter -v build apk
      
      - store_artifacts:
          path: android/build/app/outputs/apk
          destination: outputs

      - store_artifacts:
          path: android/build/reports
          destination: reports

      - store_test_results:
          path: android/build/test-results