on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

name: Mobile Build
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '9.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.17.1'
    - run: |
        cd mobile
        flutter pub get
    - run: |
        cd mobile
        flutter test
    - run: |
        cd mobile
        flutter build apk --debug --split-per-abi
    #- name: Push APK to Releases
    #  uses: ncipollo/release-action@v1
    #  with:
    #    artifacts: "build/app/outputs/apk/debug/*.apk"
    #    token: ${{ secrets.TOKEN }}
